[package]
name = "chip8_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.16"
env_logger = "0.9.0"
rand = "0.8.5"
clap = { version = "3.1.9", features = ["derive"] }
sdl2 = { version = "0.35", features = [ "bundled", "static-link" ] }
